name: Deploy site

on:
  push:
    branches:
      - claude/focused-sagan-k0fq34

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Copy files to Apache
        run: |
          rsync -av --delete --exclude='.git' --exclude='.github' --exclude='status.json' --exclude='ram-test.json' ./ /var/www/html/
